// Mocks generated by Mockito 5.4.4 from annotations
// in batch_four_exp/test/todo_repo.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:batch_four_exp/features/todo/service/todo_data.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TodoData].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoData extends _i1.Mock implements _i2.TodoData {
  MockTodoData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<String>> addTodo(
    String? todoData,
    List<String>? todoList,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTodo,
          [
            todoData,
            todoList,
          ],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<List<String>> getTodoFromServer() => (super.noSuchMethod(
        Invocation.method(
          #getTodoFromServer,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);
}
